import { StyleSheet, Platform, StatusBar } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F2F2F7',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  screenHeaderTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#000000',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 8,
    paddingHorizontal: 12,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: '#000000' },
  tabsContainer: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginVertical: 8,
    backgroundColor: '#E5E5EA',
    borderRadius: 9,
    padding: 3,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
  },
  activeTabButton: { backgroundColor: '#007AFF' },
  inactiveTabButton: { backgroundColor: 'transparent' },
  activeTabText: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
  inactiveTabText: { fontSize: 14, fontWeight: '500', color: '#8E8E93' },
  tabIcon: { marginRight: 6 },
  subFilterWrapper: { marginVertical: 4 },
  subFiltersContainer: { paddingHorizontal: 16, alignItems: 'center' },
  subFilterPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 18,
    marginRight: 8,
    borderWidth: 1,
  },
  activePill: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  inactivePill: { backgroundColor: '#FFFFFF', borderColor: '#D1D1D6' },
  activePillText: { fontSize: 13, color: '#FFFFFF', fontWeight: '600' },
  inactivePillText: { fontSize: 13, color: '#3A3A3C', fontWeight: '500' },
  highlightedText: {
    backgroundColor: '#D0E1FD',
    color: '#0056B3',
    fontWeight: '700',
    borderRadius: 2,
  },
  resultsList: { flex: 1, paddingHorizontal: 16, marginTop: 8 },
  chatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  avatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 16 },
  unreadBadge: {
    backgroundColor: '#007AFF',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
  },
  unreadBadgeText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  chatInfo: { flex: 1 },
  chatTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timeAgoText: { fontSize: 12, color: '#8E8E93' },
  chatSummary: { fontSize: 13, color: '#8E8E93', marginTop: 2 },
  matchesPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginTop: 6,
  },
  matchesPillText: { fontSize: 11, color: '#007AFF', fontWeight: '600' },
  groupCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 12,
    padding: 12,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E5EA',
    paddingBottom: 8,
    marginBottom: 8,
  },
  groupTitle: { fontSize: 15, fontWeight: '700', color: '#000000' },
  groupSubtitle: { fontSize: 11, color: '#8E8E93', marginTop: 1 },
  resultBadge: {
    backgroundColor: '#E5E5EA',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  resultBadgeText: { fontSize: 11, fontWeight: '600', color: '#3A3A3C' },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F2F2F7',
  },
  rowSecondaryNote: { fontSize: 12, color: '#8E8E93', marginTop: 2 },
  boldText: { fontSize: 14, fontWeight: '600', color: '#000000' },
  completedText: { textDecorationLine: 'line-through', color: '#8E8E93' },
  avatarCircleSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarTextSmall: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 12 },
  avatarCircleMicro: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  avatarTextMicro: { color: '#FFFFFF', fontSize: 10, fontWeight: 'bold' },
  duePill: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  duePillOverdue: { backgroundColor: '#FFEBEE' },
  duePillNormal: { backgroundColor: '#E5E5EA' },
  duePillTextOverdue: { color: '#C62828', fontSize: 10, fontWeight: '600' },
  duePillTextNormal: { color: '#3A3A3C', fontSize: 10, fontWeight: '600' },
  statusBadgeSmall: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4 },
  statusBadgeTextSmall: { fontSize: 10, fontWeight: '700' },
  amountText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#000000',
    marginLeft: 8,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5E5EA',
  },
  backButton: { flexDirection: 'row', alignItems: 'center' },
  backButtonText: { fontSize: 16, color: '#007AFF', marginLeft: 2 },
  detailHeaderTitle: { fontSize: 17, fontWeight: '600', color: '#000000' },
  sourceChatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
  },
  sourceChatTitle: { fontSize: 14, fontWeight: '600', color: '#000000' },
  sourceChatSub: { fontSize: 12, color: '#007AFF', marginTop: 1 },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8E8E93',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
    marginTop: 12,
    justifyContent: 'space-between',
  },
  gridItem: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
  },
  gridLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#8E8E93',
    marginBottom: 4,
  },
  gridValueRow: { flexDirection: 'row', alignItems: 'center' },
  gridValueText: { fontSize: 13, fontWeight: '600', color: '#000000' },
  subtaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  attachmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F7',
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  amountHeroContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    padding: 20,
    borderRadius: 12,
  },
  heroAmountText: {
    fontSize: 32,
    fontWeight: '800',
    color: '#000000',
    marginVertical: 6,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F2F2F7',
  },
  infoLabel: { fontSize: 13, color: '#8E8E93' },
  infoValue: { fontSize: 13, fontWeight: '600', color: '#000000' },
  payButton: {
    backgroundColor: '#007AFF',
    marginHorizontal: 16,
    marginVertical: 16,
    height: 50,
    borderRadius: 12,
    alignItems: 'center',
  },
  payButtonDisabled: { backgroundColor: '#B0C4DE' },
  payButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  markCompleteButton: {
    backgroundColor: '#34C759',
    marginHorizontal: 16,
    marginVertical: 16,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  markCompleteButtonDisabled: { backgroundColor: '#A8D5A2' },
  markCompleteButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 6,
  },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    paddingHorizontal: 24,
  },
  emptyText: { fontSize: 14, color: '#8E8E93', textAlign: 'center' },
  errorText: { fontSize: 14, color: '#C62828', textAlign: 'center' },
  messageBubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
    marginBottom: 8,
  },
  messageBubbleOwn: {
    backgroundColor: '#007AFF',
    alignSelf: 'flex-end',
    borderBottomRightRadius: 4,
  },
  messageBubbleOther: {
    backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 4,
  },
  messageTextOwn: { color: '#FFFFFF', fontSize: 15 },
  messageTextOther: { color: '#000000', fontSize: 15 },
  messageTime: { fontSize: 11, marginTop: 4 },
  messageTimeOwn: { color: 'rgba(255,255,255,0.7)', textAlign: 'right' },
  messageTimeOther: { color: '#8E8E93' },
  chatDetailHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 8,
  },
});